### ISSUE TITLE
Home button #issue

### ISSUE THREAD

**Issue by denprokazov** [gost402/SychyovMD#23]
I have an issue.
Your launcher set as default launcher in system. When I press home button whole screen getting black and I cannot do anything with that until I block device and unblock device or kill the application.

PLEASE HALP

**Comment by gost402** [comment]
I will fix it ASAP ;)

**Comment by denprokazov** [comment]
![image](https://user-images.githubusercontent.com/11243968/36974918-710ad9bc-2089-11e8-8337-9cbd4187cc0e.png)
